spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liPPg2Q8N6WjmfkK
            client-secret: 34e3f1e5f1e94f1b78d1284e90fef8d19acd2222
            scope: read:user, user:email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: GitHub
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id